//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.10 at 08:14:26 PM GMT 
//


package ie.gmit.sw.Model;

import java.io.Serializable;
import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;



/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="cId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="rNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bookingdate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="bookingEndDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
//Reading in the sql attributes through xml
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bId",
    "cId",
    "rNo",
    "bookingdate",
    "bookingEndDate"
})
@XmlRootElement(name = "OrderTransport")
public class OrderTransport implements Serializable{

    /**
	 * 
	 */
	
	// Setting requirements to be entered for the booking table
	private static final long serialVersionUID = 1L;
	protected int bId;
    protected int cId;
    @XmlElement(required = true)
    protected String rNo;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected Date bookingdate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected Date bookingEndDate;
    
    
    public OrderTransport() {
    	super();
    }


	public OrderTransport(int bId, int cId, String rNo, Date bookingdate, Date bookingEndDate) {
		super();
		this.bId = bId;
		this.cId = cId;
		this.rNo = rNo;
		this.bookingdate = bookingdate;
		this.bookingEndDate = bookingEndDate;
	}

	/**
     * Gets the value of the bId property.
     * 
     */
    public int getBId() {
        return bId;
    }

    /**
     * Sets the value of the bId property.
     * 
     */
    public void setBId(int value) {
        this.bId = value;
    }

    /**
     * Gets the value of the cId property.
     * 
     */
    public int getCId() {
        return cId;
    }

    /**
     * Sets the value of the cId property.
     * 
     */
    public void setCId(int value) {
        this.cId = value;
    }

    /**
     * Gets the value of the rNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRNo() {
        return rNo;
    }

    /**
     * Sets the value of the rNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRNo(String value) {
        this.rNo = value;
    }

    /**
     * Gets the value of the bookingdate property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getBookingdate() {
        return bookingdate;
    }

    /**
     * Sets the value of the bookingdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setBookingdate(Date value) {
        this.bookingdate = value;
    }

    /**
     * Gets the value of the bookingEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getBookingEndDate() {
        return bookingEndDate;
    }

    /**
     * Sets the value of the bookingEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setBookingEndDate(Date value) {
        this.bookingEndDate = value;
    }
    
    @Override
	public String toString() {
		return "OrderTransport [bId=" + bId + ", cId=" + cId + ", rNo=" + rNo + ", bookingdate=" + bookingdate
				+ ", bookingEndDate=" + bookingEndDate + "]";
	}


}
